<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE freefour [
<!ELEMENT freefour (book*)>
<!ELEMENT book (Title, Tagline, AuthorL, AuthorF, Date, Pages, ISBN?, ASIN?, FakeISBN?, Notes?)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Tagline (#PCDATA)>
<!ELEMENT AuthorL (#PCDATA)>
<!ELEMENT AuthorF (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Pages (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT ASIN (#PCDATA)>
<!ELEMENT FakeISBN (#PCDATA)>
<!ELEMENT Notes (#PCDATA)>
]>
<?xml-stylesheet type="text/xsl" href="booksRead.xsl"?>

<!--
- Database: 'freefour'
-->
<freefour>
	<!-- Table books -->
	<book>
		<Title>James and the Giant Peach</Title>
		<Tagline></Tagline>
		<AuthorL>Dahl</AuthorL>
		<AuthorF>Roald</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>119</Pages>
		<ISBN>0-14-032871-8</ISBN>
	</book>
	<book>
		<Title>1984</Title>
		<Tagline></Tagline>
		<AuthorL>Orwell</AuthorL>
		<AuthorF>George</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>268</Pages>
		<ISBN>0-451-52493-4</ISBN>
	</book>
	<book>
		<Title>20,000 Leagues Under the Sea</Title>
		<Tagline></Tagline>
		<AuthorL>Verne</AuthorL>
		<AuthorF>Jules</AuthorF>
		<Date>1995-00-00</Date>
		<Pages>384</Pages>
		<ISBN>9780760728505</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Adventures of Huckleberry Finn, The</Title>
		<Tagline></Tagline>
		<AuthorL>Twain</AuthorL>
		<AuthorF>Mark</AuthorF>
		<Date>1998-00-00</Date>
		<Pages>336</Pages>
		<ISBN>0-448-11000-8</ISBN>
	</book>
	<book>
		<Title>Heart of Darkness</Title>
		<Tagline></Tagline>
		<AuthorL>Conrad</AuthorL>
		<AuthorF>Joseph</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>158</Pages>
		<ISBN>0-451-52072-6</ISBN>
	</book>
	<book>
		<Title>Age of Spiritual Machines, The</Title>
		<Tagline>When Computers Exceed Human Intelligence</Tagline>
		<AuthorL>Kurzweil</AuthorL>
		<AuthorF>Raymond</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>388</Pages>
		<ISBN>0-14-028202-5</ISBN>
	</book>
	<book>
		<Title>Alas, Babylon</Title>
		<Tagline></Tagline>
		<AuthorL>Frank</AuthorL>
		<AuthorF>Pat</AuthorF>
		<Date>1997-00-00</Date>
		<Pages>323</Pages>
		<ISBN>0-06-081254-0</ISBN>
	</book>
	<book>
		<Title>All Quiet on the Western Front</Title>
		<Tagline></Tagline>
		<AuthorL>Remarque</AuthorL>
		<AuthorF>Erich</AuthorF>
		<Date>1997-00-00</Date>
		<Pages>295</Pages>
		<ISBN>0-449-21394-3</ISBN>
	</book>
	<book>
		<Title>Amazing Real Life Coincidences</Title>
		<Tagline></Tagline>
		<AuthorL>Colligan</AuthorL>
		<AuthorF>Douglas</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>134</Pages>
	</book>
	<book>
		<Title>Angels in America</Title>
		<Tagline>Millenium Approaches</Tagline>
		<AuthorL>Kushner</AuthorL>
		<AuthorF>Tony</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>119</Pages>
		<ISBN>1-55936-061-5</ISBN>
	</book>
	<book>
		<Title>Copenhagen</Title>
		<Tagline></Tagline>
		<AuthorL>Frayn</AuthorL>
		<AuthorF>Michael</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>132</Pages>
		<ISBN>0-385-72079-3</ISBN>
	</book>
	<book>
		<Title>Wit</Title>
		<Tagline></Tagline>
		<AuthorL>Edson</AuthorL>
		<AuthorF>Margaret</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>85</Pages>
		<ISBN>0-571-19877-5</ISBN>
	</book>
	<book>
		<Title>Dr. Faustus</Title>
		<Tagline></Tagline>
		<AuthorL>Marlowe</AuthorL>
		<AuthorF>Christopher</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>56</Pages>
		<ISBN>978-0486282084</ISBN>
	</book>
	<book>
		<Title>Animal Farm</Title>
		<Tagline></Tagline>
		<AuthorL>Orwell</AuthorL>
		<AuthorF>George</AuthorF>
		<Date>1996-00-00</Date>
		<Pages>140</Pages>
	</book>
	<book>
		<Title>Around the World in Eighty Days</Title>
		<Tagline></Tagline>
		<AuthorL>Verne</AuthorL>
		<AuthorF>Jules</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>240</Pages>
	</book>
	<book>
		<Title>Atlas Shrugged</Title>
		<Tagline></Tagline>
		<AuthorL>Rand</AuthorL>
		<AuthorF>Ayn</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>1075</Pages>
	</book>
	<book>
		<Title>Bit and the Pendulum, The</Title>
		<Tagline>From Quantum Computing to M Theory--The New Physics of Information</Tagline>
		<AuthorL>Siegfried</AuthorL>
		<AuthorF>Tom</AuthorF>
		<Date>2001-10-18</Date>
		<Pages>288</Pages>
		<ISBN>9780471399742</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Black Like Me</Title>
		<Tagline></Tagline>
		<AuthorL>Griffin</AuthorL>
		<AuthorF>John</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>192</Pages>
	</book>
	<book>
		<Title>Book of Greek Myths</Title>
		<Tagline></Tagline>
		<AuthorL>D'aulaires</AuthorL>
		<AuthorF>Ingri</AuthorF>
		<Date>1994-00-00</Date>
		<Pages>192</Pages>
	</book>
	<book>
		<Title>Bridge To Terabithia</Title>
		<Tagline></Tagline>
		<AuthorL>Paterson</AuthorL>
		<AuthorF>Katherine</AuthorF>
		<Date>1995-00-00</Date>
		<Pages>144</Pages>
	</book>
	<book>
		<Title>Brief History of Time, A</Title>
		<Tagline></Tagline>
		<AuthorL>Hawking</AuthorL>
		<AuthorF>Steven</AuthorF>
		<Date>2001-06-20</Date>
		<Pages>212</Pages>
		<ISBN>0553346148</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Call of the Wild</Title>
		<Tagline></Tagline>
		<AuthorL>London</AuthorL>
		<AuthorF>Jack</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>114</Pages>
	</book>
	<book>
		<Title>Can Animals and Machines be Persons?</Title>
		<Tagline></Tagline>
		<AuthorL>Leiber</AuthorL>
		<AuthorF>Justin</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>76</Pages>
		<ISBN>0-87220-002-7</ISBN>
	</book>
	<book>
		<Title>Classic Philip Jose Farmer, The</Title>
		<Tagline>1964-1973</Tagline>
		<AuthorL>Farmer</AuthorL>
		<AuthorF>Philip Jose</AuthorF>
		<Date>2005-11-27</Date>
		<Pages>207</Pages>
		<ISBN>9780517555453</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Chaos</Title>
		<Tagline>Making a New Science</Tagline>
		<AuthorL>Gleick</AuthorL>
		<AuthorF>James</AuthorF>
		<Date>2001-05-28</Date>
		<Pages>352</Pages>
	</book>
	<book>
		<Title>Cognition</Title>
		<Tagline>Exploring the Science of the Mind</Tagline>
		<AuthorL>Reisberg</AuthorL>
		<AuthorF>Daniel</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>500</Pages>
		<ISBN>0-393-96925-8</ISBN>
	</book>
	<book>
		<Title>Computer Hardware, System Software, and Architecture</Title>
		<Tagline></Tagline>
		<AuthorL>Luce</AuthorL>
		<AuthorF></AuthorF>
		<Date>1996-00-00</Date>
		<Pages>0</Pages>
	</book>
	<book>
		<Title>Country Year, A</Title>
		<Tagline>Living the Questions</Tagline>
		<AuthorL>Hubbell</AuthorL>
		<AuthorF>Sue</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>240</Pages>
	</book>
	<book>
		<Title>Crash Course in Artificial Intelligence and Expert Systems</Title>
		<Tagline></Tagline>
		<AuthorL>Frenzel</AuthorL>
		<AuthorF>Louis</AuthorF>
		<Date>2001-09-06</Date>
		<Pages>358</Pages>
		<ISBN>9780672224430</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Critiques of God</Title>
		<Tagline>Making the Case Against Belief in God</Tagline>
		<AuthorL>Angeles</AuthorL>
		<AuthorF>Peter</AuthorF>
		<Date>2001-06-01</Date>
		<Pages>371</Pages>
		<ISBN>9781573921237</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Darkness Visible</Title>
		<Tagline>A Memoir of Madness</Tagline>
		<AuthorL>Styron</AuthorL>
		<AuthorF>William</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>84</Pages>
	</book>
	<book>
		<Title>Data Compression</Title>
		<Tagline>Techniques and Applications - Hardware and Software Considerations</Tagline>
		<AuthorL>Held</AuthorL>
		<AuthorF>Gilbert</AuthorF>
		<Date>2001-09-16</Date>
		<Pages>301</Pages>
		<ISBN>9780471929413</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Data Compression</Title>
		<Tagline>The Complete Reference</Tagline>
		<AuthorL>Salomon</AuthorL>
		<AuthorF>David</AuthorF>
		<Date>2002-02-12</Date>
		<Pages>792</Pages>
		<ISBN>9780387406978</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Defeating Darwinism</Title>
		<Tagline></Tagline>
		<AuthorL>Johnson</AuthorL>
		<AuthorF>Phillip</AuthorF>
		<Date>2001-05-25</Date>
		<Pages>131</Pages>
	</book>
	<book>
		<Title>Doll's House, A</Title>
		<Tagline></Tagline>
		<AuthorL>Ibsen</AuthorL>
		<AuthorF>Henrik</AuthorF>
		<Date>1997-00-00</Date>
		<Pages>0</Pages>
	</book>
	<book>
		<Title>Dr. Jekyll and Mr. Hyde</Title>
		<Tagline></Tagline>
		<AuthorL>Stevenson</AuthorL>
		<AuthorF>Robert</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>82</Pages>
	</book>
	<book>
		<Title>Duplicate, The</Title>
		<Tagline></Tagline>
		<AuthorL>Sleator</AuthorL>
		<AuthorF>William</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>154</Pages>
	</book>
	<book>
		<Title>Engines of Creation</Title>
		<Tagline>The Coming Era of Nanotechnology</Tagline>
		<AuthorL>Drexler</AuthorL>
		<AuthorF>K. Eric</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>320</Pages>
	</book>
	<book>
		<Title>Enoch Arden, The Holy Grail, and Other Poems</Title>
		<Tagline></Tagline>
		<AuthorL>Tennyson</AuthorL>
		<AuthorF>Alfred Lord</AuthorF>
		<Date>2001-05-16</Date>
		<Pages>126</Pages>
		<Notes>
			Hardcover
			Riverside Literature Series
			With Explanatory Notes
			Copyright 1895, 1914
			Houghton Mifflin Company
			Riverside Press, The
			Cambridge, Mass
		</Notes>
	</book>
	<book>
		<Title>Essential Dali</Title>
		<Tagline></Tagline>
		<AuthorL>Bradbury</AuthorL>
		<AuthorF>Kirsten</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>256</Pages>
	</book>
	<book>
		<Title>Ethan Frome</Title>
		<Tagline></Tagline>
		<AuthorL>Wharton</AuthorL>
		<AuthorF>Edith</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>182</Pages>
	</book>
	<book>
		<Title>Fellowship of the Ring, The</Title>
		<Tagline></Tagline>
		<AuthorL>Tolkien</AuthorL>
		<AuthorF>J. R. R.</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>398</Pages>
	</book>
	<book>
		<Title>Flowers for Algernon</Title>
		<Tagline></Tagline>
		<AuthorL>Keyes</AuthorL>
		<AuthorF>Daniel</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>328</Pages>
	</book>
	<book>
		<Title>For Whom the Bell Tolls</Title>
		<Tagline></Tagline>
		<AuthorL>Hemingway</AuthorL>
		<AuthorF>Ernest</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>471</Pages>
	</book>
	<book>
		<Title>From the Earth to the Moon</Title>
		<Tagline></Tagline>
		<AuthorL>Verne</AuthorL>
		<AuthorF>Jules</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>242</Pages>
		<ISBN>0-553-21420-9</ISBN>
	</book>
	<book>
		<Title>Genius</Title>
		<Tagline>The Life and Science of Richard Feynman</Tagline>
		<AuthorL>Gleick</AuthorL>
		<AuthorF>James</AuthorF>
		<Date>2002-02-03</Date>
		<Pages>531</Pages>
		<ISBN>9780679747048</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Giver, The</Title>
		<Tagline></Tagline>
		<AuthorL>Lowry</AuthorL>
		<AuthorF>Lois</AuthorF>
		<Date>1995-00-00</Date>
		<Pages>180</Pages>
	</book>
	<book>
		<Title>Gödel, Escher, Bach</Title>
		<Tagline>Eternal Golden Braid</Tagline>
		<AuthorL>Hofstadter</AuthorL>
		<AuthorF>Douglas</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>777</Pages>
		<ISBN>0-394-74502-7</ISBN>
	</book>
	<book>
		<Title>Gödel's Proof</Title>
		<Tagline></Tagline>
		<AuthorL>Nagel</AuthorL>
		<AuthorF>Ernest</AuthorF>
		<Date>1999-07-00</Date>
		<Pages>125</Pages>
		<ISBN>0-8147-5816-9</ISBN>
	</book>
	<book>
		<Title>God's Debris</Title>
		<Tagline></Tagline>
		<AuthorL>Adams</AuthorL>
		<AuthorF>Scott</AuthorF>
		<Date>2001-06-01</Date>
		<Pages>144</Pages>
		<ISBN>0740747878</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Good Earth, The</Title>
		<Tagline></Tagline>
		<AuthorL>Buck</AuthorL>
		<AuthorF>Pearl</AuthorF>
		<Date>1995-00-00</Date>
		<Pages>379</Pages>
		<ISBN>0671729896</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Great Gatsby, The</Title>
		<Tagline></Tagline>
		<AuthorL>Fitzgerald</AuthorL>
		<AuthorF>F. Scott</AuthorF>
		<Date>1998-00-00</Date>
		<Pages>216</Pages>
		<ISBN>0-684-80152-3</ISBN>
	</book>
	<book>
		<Title>Great Mambo Chicken and the Transhuman Condition</Title>
		<Tagline>Science Slightly over the Edge</Tagline>
		<AuthorL>Regis</AuthorL>
		<AuthorF>Ed</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>308</Pages>
		<ISBN>9780201567519</ISBN>
	</book>
	<book>
		<Title>Great Tales and Poems of Edgar Allan Poe</Title>
		<Tagline></Tagline>
		<AuthorL>Poe</AuthorL>
		<AuthorF>Edgar Allan</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>236</Pages>
		<ISBN>0743467469</ISBN>
		<FakeISBN/>
		<Notes>
			ISBN on back of book says 1-55902-983-8, but was apparently reused by Wallmart publishing
		</Notes>
	</book>
	<book>
		<Title>Growing up Digital</Title>
		<Tagline>The Rise of the Net Generation</Tagline>
		<AuthorL>Tapscott</AuthorL>
		<AuthorF>Don</AuthorF>
		<Date>2001-10-26</Date>
		<Pages>336</Pages>
		<ISBN>9780070633612</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Hard Disk Power</Title>
		<Tagline></Tagline>
		<AuthorL>Jamsa</AuthorL>
		<AuthorF>Kris</AuthorF>
		<Date>1997-00-00</Date>
		<Pages>442</Pages>
		<ISBN>0-672-22761-4</ISBN>
	</book>
	<book>
		<Title>Heart of the Matter, The</Title>
		<Tagline></Tagline>
		<AuthorL>Greene</AuthorL>
		<AuthorF>Graham</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>240</Pages>
		<ISBN>9780140184969</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Ideas and Opinions</Title>
		<Tagline></Tagline>
		<AuthorL>Einstein</AuthorL>
		<AuthorF>Albert</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>384</Pages>
	</book>
	<book>
		<Title>Imaginary Numbers</Title>
		<Tagline>An Anthology of Marvelous Mathematical Stories, Diversions, Poems, and Musings</Tagline>
		<AuthorL>Frucht</AuthorL>
		<AuthorF>William</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>360</Pages>
	</book>
	<book>
		<Title>In Quest of Ghosts</Title>
		<Tagline></Tagline>
		<AuthorL>Holzer</AuthorL>
		<AuthorF>Hans</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>215</Pages>
	</book>
	<book>
		<Title>Infinity</Title>
		<Tagline></Tagline>
		<AuthorL>Lieber</AuthorL>
		<AuthorF>Lillian</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>0</Pages>
	</book>
	<book>
		<Title>Into the Heart of the Mind</Title>
		<Tagline>An American Quest for Artificial Intelligence</Tagline>
		<AuthorL>Rose</AuthorL>
		<AuthorF>Frank</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>209</Pages>
		<ISBN>0-06-015306-7</ISBN>
	</book>
	<!--<book>
		<Title>IntranetWare</Title>
		<Tagline>NetWare 4.11 Administration</Tagline>
		<AuthorL></AuthorL>
		<AuthorF></AuthorF>
		<Date>1998-00-00</Date>
		<Pages>0</Pages>
	</book>-->
	<book>
		<Title>Introduction to Modern Biology, An</Title>
		<Tagline></Tagline>
		<AuthorL>Bailey &amp; Wagner</AuthorL>
		<AuthorF></AuthorF>
		<Date>0000-00-00</Date>
		<Pages>520</Pages>
	</book>
	<book>
		<Title>Invisible Man, The</Title>
		<Tagline></Tagline>
		<AuthorL>Wells</AuthorL>
		<AuthorF>H. G.</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>196</Pages>
	</book>
	<book>
		<Title>Ironweed</Title>
		<Tagline></Tagline>
		<AuthorL>Kennedy</AuthorL>
		<AuthorF>William</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>227</Pages>
	</book>
	<book>
		<Title>Jane Eyre</Title>
		<Tagline></Tagline>
		<AuthorL>Bronte</AuthorL>
		<AuthorF>Charlotte</AuthorF>
		<Date>1998-00-00</Date>
		<Pages>461</Pages>
	</book>
	<book>
		<Title>Journal of the Plague Year, A</Title>
		<Tagline></Tagline>
		<AuthorL>Defoe</AuthorL>
		<AuthorF>Daniel</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>256</Pages>
	</book>
	<book>
		<Title>Journey to the Center of the Earth, A</Title>
		<Tagline></Tagline>
		<AuthorL>Verne</AuthorL>
		<AuthorF>Jules</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>0</Pages>
	</book>
	<book>
		<Title>Just for Fun</Title>
		<Tagline>The Story of an Accidental Revolutionary</Tagline>
		<AuthorL>Torvalds</AuthorL>
		<AuthorF>Linus</AuthorF>
		<Date>2001-09-11</Date>
		<Pages>288</Pages>
		<ISBN>9780066620725</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>King Lear</Title>
		<Tagline></Tagline>
		<AuthorL>Shakespeare</AuthorL>
		<AuthorF>William</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>118</Pages>
		<ISBN>0-486-28058-6</ISBN>
	</book>
	<book>
		<Title>Molly Sweeney</Title>
		<Tagline></Tagline>
		<AuthorL>Friel</AuthorL>
		<AuthorF>Brian</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>70</Pages>
		<ISBN>0452275083</ISBN>
	</book>
	<book>
		<Title>Galileo</Title>
		<Tagline></Tagline>
		<AuthorL>Brecht</AuthorL>
		<AuthorF>Bertolt</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>155</Pages>
		<ISBN>0802130593</ISBN>
	</book>
	<book>
		<Title>Arcadia</Title>
		<Tagline></Tagline>
		<AuthorL>Stoppard</AuthorL>
		<AuthorF>Tom</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>97</Pages>
		<ISBN>0-571-16934-1</ISBN>
	</book>
	<book>
		<Title>Physicists, The</Title>
		<Tagline></Tagline>
		<AuthorL>Durrenmatt</AuthorL>
		<AuthorF>Friedrich</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>94</Pages>
		<ISBN>0802150888</ISBN>
	</book>
	<book>
		<Title>Little Prince, The</Title>
		<Tagline></Tagline>
		<AuthorL>St. Exupery</AuthorL>
		<AuthorF>Antoine</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>96</Pages>
	</book>
	<book>
		<Title>Lives of a Cell</Title>
		<Tagline></Tagline>
		<AuthorL>Thomas</AuthorL>
		<AuthorF>Lewis</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>153</Pages>
	</book>
	<book>
		<Title>Locked in Time</Title>
		<Tagline></Tagline>
		<AuthorL>Duncan</AuthorL>
		<AuthorF>Lois</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>210</Pages>
	</book>
	<book>
		<Title>Lord of the Flies</Title>
		<Tagline></Tagline>
		<AuthorL>Golding</AuthorL>
		<AuthorF>William</AuthorF>
		<Date>1997-00-00</Date>
		<Pages>208</Pages>
	</book>
	<book>
		<Title>Metamagical Themas</Title>
		<Tagline>Questing for the Essence of Mind and Pattern</Tagline>
		<AuthorL>Hofstadter</AuthorL>
		<AuthorF>Douglas</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>880</Pages>
	</book>
	<book>
		<Title>Midnight in the Garden of Good and Evil</Title>
		<Tagline></Tagline>
		<AuthorL>Berendt</AuthorL>
		<AuthorF>John</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>386</Pages>
	</book>
	<book>
		<Title>Mind's I, The</Title>
		<Tagline>Fantasies and Reflections on Self &amp; Soul</Tagline>
		<AuthorL>Hofstadter</AuthorL>
		<AuthorF>Douglas</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>500</Pages>
		<ISBN>0-553-34584-2</ISBN>
	</book>
	<book>
		<Title>Mysterious Island, The</Title>
		<Tagline></Tagline>
		<AuthorL>Verne</AuthorL>
		<AuthorF>Jules</AuthorF>
		<Date>1995-00-00</Date>
		<Pages>640</Pages>
		<ISBN>0-451-52491-8</ISBN>
	</book>
	<book>
		<Title>Nectar in a Sieve</Title>
		<Tagline></Tagline>
		<AuthorL>Markandaya</AuthorL>
		<AuthorF>Kamala</AuthorF>
		<Date>1997-00-00</Date>
		<Pages>208</Pages>
	</book>
	<book>
		<Title>Night</Title>
		<Tagline></Tagline>
		<AuthorL>Wiesel</AuthorL>
		<AuthorF>Elie</AuthorF>
		<Date>1997-00-00</Date>
		<Pages>109</Pages>
	</book>
	<book>
		<Title>No Ordinary Genius</Title>
		<Tagline>The Illustrated Richard Feynman</Tagline>
		<AuthorL>Sykes</AuthorL>
		<AuthorF>Christopher</AuthorF>
		<Date>2002-01-27</Date>
		<Pages>272</Pages>
		<ISBN>9780393313932</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Old Man and the Sea, The</Title>
		<Tagline></Tagline>
		<AuthorL>Hemingway</AuthorL>
		<AuthorF>Ernest</AuthorF>
		<Date>1995-00-00</Date>
		<Pages>96</Pages>
		<ISBN>9780684830490</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>On the Origin of Species</Title>
		<Tagline></Tagline>
		<AuthorL>Darwin</AuthorL>
		<AuthorF>Charles</AuthorF>
		<Date>2001-06-06</Date>
		<Pages>352</Pages>
		<ISBN>9780451605030</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>On the Road</Title>
		<Tagline></Tagline>
		<AuthorL>Kerouac</AuthorL>
		<AuthorF>Jack</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>310</Pages>
		<ISBN>0-14-004259-8</ISBN>
	</book>
	<book>
		<Title>Out of Africa</Title>
		<Tagline></Tagline>
		<AuthorL>Dinesen</AuthorL>
		<AuthorF>Isak</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>462</Pages>
		<ISBN>0-679-72475-3</ISBN>
	</book>
	<book>
		<Title>Peter Pan</Title>
		<Tagline></Tagline>
		<AuthorL>Barrie</AuthorL>
		<AuthorF>J. M.</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>192</Pages>
	</book>
	<book>
		<Title>Phantom Tollbooth, The</Title>
		<Tagline></Tagline>
		<AuthorL>Juster</AuthorL>
		<AuthorF>Norton</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>256</Pages>
	</book>
	<book>
		<Title>Photoshop Web Techniques</Title>
		<Tagline></Tagline>
		<AuthorL>Hamlin</AuthorL>
		<AuthorF></AuthorF>
		<Date>0000-00-00</Date>
		<Pages>0</Pages>
	</book>
	<book>
		<Title>Programmer's Introduction to PHP 4.0, A</Title>
		<Tagline></Tagline>
		<AuthorL>Gilmore</AuthorL>
		<AuthorF>W. J.</AuthorF>
		<Date>2001-09-24</Date>
		<Pages>430</Pages>
	</book>
	<book>
		<Title>Random Essays On Mathematics, Education, and Computers</Title>
		<Tagline></Tagline>
		<AuthorL>Kemeny</AuthorL>
		<AuthorF>John</AuthorF>
		<Date>2001-11-12</Date>
		<Pages>163</Pages>
		<ASIN>B0006BLZW0</ASIN>
	</book>
	<book>
		<Title>Recursive Universe, The</Title>
		<Tagline>Cosmic Complexity and the Limits of Scientific Knowledge</Tagline>
		<AuthorL>Poundstone</AuthorL>
		<AuthorF>William</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>0</Pages>
	</book>
	<book>
		<Title>Red Badge of Courage, The</Title>
		<Tagline></Tagline>
		<AuthorL>Crane</AuthorL>
		<AuthorF>Stephen</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>100</Pages>
	</book>
	<book>
		<Title>Relativity for the Million</Title>
		<Tagline></Tagline>
		<AuthorL>Gardner</AuthorL>
		<AuthorF>Martin</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>182</Pages>
	</book>
	<book>
		<Title>Riddles in Mathematics</Title>
		<Tagline></Tagline>
		<AuthorL>Northrop</AuthorL>
		<AuthorF></AuthorF>
		<Date>1999-00-00</Date>
		<Pages>244</Pages>
	</book>
	<book>
		<Title>Robinson Crusoe</Title>
		<Tagline></Tagline>
		<AuthorL>DeFoe</AuthorL>
		<AuthorF>Daniel</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>337</Pages>
		<ISBN>1-55902-983-8</ISBN>
	</book>
	<book>
		<Title>Romeo and Juliet</Title>
		<Tagline></Tagline>
		<AuthorL>Shakespeare</AuthorL>
		<AuthorF></AuthorF>
		<Date>1996-00-00</Date>
		<Pages>0</Pages>
	</book>
	<book>
		<Title>Scarlet Letter, The</Title>
		<Tagline></Tagline>
		<AuthorL>Hawthorne</AuthorL>
		<AuthorF>Nathaniel</AuthorF>
		<Date>1998-00-00</Date>
		<Pages>180</Pages>
		<ISBN>0-486-28048-9</ISBN>
	</book>
	<book>
		<Title>Scary Stories Treasury, The</Title>
		<Tagline></Tagline>
		<AuthorL>Schwartz &amp; Gammell</AuthorL>
		<AuthorF></AuthorF>
		<Date>0000-00-00</Date>
		<Pages>320</Pages>
	</book>
	<book>
		<Title>Second Self, The</Title>
		<Tagline>Computers and the Human Spirit</Tagline>
		<AuthorL>Turkle</AuthorL>
		<AuthorF>Sherry</AuthorF>
		<Date>1999-07-00</Date>
		<Pages>362</Pages>
	</book>
	<book>
		<Title>Selfish Gene, The</Title>
		<Tagline></Tagline>
		<AuthorL>Dawkins</AuthorL>
		<AuthorF>Richard</AuthorF>
		<Date>2001-10-04</Date>
		<Pages>352</Pages>
		<ISBN>9780192177735</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Separate Peace, A</Title>
		<Tagline></Tagline>
		<AuthorL>Knowles</AuthorL>
		<AuthorF>John</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>196</Pages>
	</book>
	<book>
		<Title>Significance of Mathematics, The</Title>
		<Tagline></Tagline>
		<AuthorL>Montague</AuthorL>
		<AuthorF>Harriet</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>0</Pages>
	</book>
	<book>
		<Title>Silence of the Lambs, The</Title>
		<Tagline></Tagline>
		<AuthorL>Harris</AuthorL>
		<AuthorF>Thomas</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>367</Pages>
	</book>
	<book>
		<Title>Stairway to Hell</Title>
		<Tagline>The Well-Planned Destruction of Teens</Tagline>
		<AuthorL>Jones</AuthorL>
		<AuthorF>Rick</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>0</Pages>
	</book>
	<book>
		<Title>Tao of Physics, The</Title>
		<Tagline>An Exploration of the Parallels Between Modern Physics and Eastern Mysticism</Tagline>
		<AuthorL>Capra</AuthorL>
		<AuthorF>Fritjof</AuthorF>
		<Date>2001-06-17</Date>
		<Pages>368</Pages>
		<ISBN>9781570625190</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Tao Te Ching</Title>
		<Tagline></Tagline>
		<AuthorL>Rosenthal</AuthorL>
		<AuthorF>Stan</AuthorF>
		<Date>2001-06-19</Date>
		<Pages>176</Pages>
		<ISBN>9780679776192</ISBN>
		<FakeISBN/>
		<Notes>
			Rosenthal version is just an e-book, no isbn exists
		</Notes>
	</book>
	<book>
		<Title>Things Fall Apart</Title>
		<Tagline></Tagline>
		<AuthorL>Achebe</AuthorL>
		<AuthorF>Chinua</AuthorF>
		<Date>1997-00-00</Date>
		<Pages>209</Pages>
	</book>
	<book>
		<Title>Thinking Computers and Virtual Persons</Title>
		<Tagline>Essays on the Intentionality of Machines</Tagline>
		<AuthorL>Dietrich</AuthorL>
		<AuthorF>Eric</AuthorF>
		<Date>2001-10-19</Date>
		<Pages>363</Pages>
		<ISBN>9780122154959</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Time Machine, The</Title>
		<Tagline></Tagline>
		<AuthorL>Wells</AuthorL>
		<AuthorF>H. G.</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>120</Pages>
		<ISBN>9780451528551</ISBN>
		<FakeISBN/>
		<Notes>
			ISBN on back of book says 1-55902-983-8, but was apparently reused by Wallmart publishing
		</Notes>
	</book>
	<book>
		<Title>To Kill a Mockingbird</Title>
		<Tagline></Tagline>
		<AuthorL>Lee</AuthorL>
		<AuthorF>Harper</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>281</Pages>
	</book>
	<book>
		<Title>Truth from Trash</Title>
		<Tagline>How Learning Makes Sense</Tagline>
		<AuthorL>Thornton</AuthorL>
		<AuthorF>Chris</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>216</Pages>
	</book>
	<book>
		<Title>Ultimate Hitchhiker's Guide, The</Title>
		<Tagline></Tagline>
		<AuthorL>Adams</AuthorL>
		<AuthorF>Douglas</AuthorF>
		<Date>1999-00-00</Date>
		<Pages>815</Pages>
		<ISBN>0-517-14925-7</ISBN>
	</book>
	<book>
		<Title>Walden Pond</Title>
		<Tagline></Tagline>
		<AuthorL>Thoreau</AuthorL>
		<AuthorF>Henry</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>221</Pages>
		<ISBN>9780451513397</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>War of the Worlds, The</Title>
		<Tagline></Tagline>
		<AuthorL>Wells</AuthorL>
		<AuthorF>H. G.</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>204</Pages>
	</book>
	<book>
		<Title>What Do You Care what Other People Think?</Title>
		<Tagline>Further Adventures of a Curious Character</Tagline>
		<AuthorL>Leighton</AuthorL>
		<AuthorF>Ralph</AuthorF>
		<Date>2002-01-25</Date>
		<Pages>256</Pages>
		<ISBN>9780553347845</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>White Fang</Title>
		<Tagline></Tagline>
		<AuthorL>London</AuthorL>
		<AuthorF>Jack</AuthorF>
		<Date>0000-00-00</Date>
		<Pages>271</Pages>
	</book>
	<book>
		<Title>Why People Believe Weird Things</Title>
		<Tagline>Pseudoscience, Superstition, and Other Confusions of Our Time</Tagline>
		<AuthorL>Shermer</AuthorL>
		<AuthorF>Michael</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>306</Pages>
	</book>
	<book>
		<Title>Winesburg, Ohio</Title>
		<Tagline></Tagline>
		<AuthorL>Anderson</AuthorL>
		<AuthorF>Sherwood</AuthorF>
		<Date>1998-00-00</Date>
		<Pages>247</Pages>
	</book>
	<book>
		<Title>Woman's Day Book of House Plants</Title>
		<Tagline></Tagline>
		<AuthorL>Hersey</AuthorL>
		<AuthorF>Jean</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>121</Pages>
	</book>
	<book>
		<Title>Writing Life, A</Title>
		<Tagline></Tagline>
		<AuthorL>Dillard</AuthorL>
		<AuthorF>Annie</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>128</Pages>
	</book>
	<book>
		<Title>Zen and the Art of Motorcycle Maintenance</Title>
		<Tagline></Tagline>
		<AuthorL>Pirsig</AuthorL>
		<AuthorF>Robert</AuthorF>
		<Date>2000-00-00</Date>
		<Pages>380</Pages>
	</book>
	<book>
		<Title>Humble Pi</Title>
		<Tagline>The Role Mathematics Should Play in American Education</Tagline>
		<AuthorL>Smith</AuthorL>
		<AuthorF>Michael</AuthorF>
		<Date>2002-03-27</Date>
		<Pages>218</Pages>
		<ISBN>9780879758776</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Travels to the Nanoworld</Title>
		<Tagline>Miniature Machinery in Nature and Technology</Tagline>
		<AuthorL>Gross</AuthorL>
		<AuthorF>Michael</AuthorF>
		<Date>2002-08-23</Date>
		<Pages>250</Pages>
		<ISBN>9780738204444</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Friendship</Title>
		<Tagline>Philosophical Reflections on a Perennial Concern</Tagline>
		<AuthorL>Blosser</AuthorL>
		<AuthorF>Philip</AuthorF>
		<Date>2002-00-00</Date>
		<Pages>440</Pages>
		<ISBN>9780761808183</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>In the Image of the Brain</Title>
		<Tagline>Breaking the Barrier Between the Human Mind and Intelligent Machines</Tagline>
		<AuthorL>Jubak</AuthorL>
		<AuthorF>Jim</AuthorF>
		<Date>2002-07-00</Date>
		<Pages>348</Pages>
		<ISBN>9780788156137</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Cyberpunk</Title>
		<Tagline>Outlaws and Hackers on the Computer Frontier</Tagline>
		<AuthorL>Hafner &amp; Markoff</AuthorL>
		<AuthorF></AuthorF>
		<Date>2002-08-27</Date>
		<Pages>400</Pages>
		<ISBN>9780684818627</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>AI</Title>
		<Tagline>The Tumultuous History of the Search for Artificial Intelligence</Tagline>
		<AuthorL>Crevier</AuthorL>
		<AuthorF>Daniel</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>0</Pages>
	</book>
	<book>
		<Title>What School Is For</Title>
		<Tagline></Tagline>
		<AuthorL>Chanan</AuthorL>
		<AuthorF>Gabriel</AuthorF>
		<Date>2002-10-07</Date>
		<Pages>129</Pages>
		<ISBN>9780416785104</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Two Towers, The</Title>
		<Tagline></Tagline>
		<AuthorL>Tolkien</AuthorL>
		<AuthorF>J. R. R.</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>415</Pages>
	</book>
	<book>
		<Title>Return of the King, The</Title>
		<Tagline></Tagline>
		<AuthorL>Tolkien</AuthorL>
		<AuthorF>J. R. R.</AuthorF>
		<Date>2001-00-00</Date>
		<Pages>507</Pages>
	</book>
	<book>
		<Title>Infinite Jest</Title>
		<Tagline></Tagline>
		<AuthorL>Wallace</AuthorL>
		<AuthorF>David</AuthorF>
		<Date>2002-10-17</Date>
		<Pages>1079</Pages>
		<ISBN>9780316920049</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Zero To Infinity, From</Title>
		<Tagline>What Makes Numbers Interesting</Tagline>
		<AuthorL>Reid</AuthorL>
		<AuthorF>Constance</AuthorF>
		<Date>2002-11-07</Date>
		<Pages>153</Pages>
		<ISBN>9780883855058</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Innumeracy</Title>
		<Tagline>Mathematical Illiteracy and Its Consequences</Tagline>
		<AuthorL>Paulos</AuthorL>
		<AuthorF>John</AuthorF>
		<Date>2002-11-11</Date>
		<Pages>135</Pages>
		<ISBN>9780809058402</ISBN>
		<FakeISBN/>
	</book>
	<book>
		<Title>Man Who Loved Only Numbers, The</Title>